export const Action = {
  GET_CITIES: "GET_CITIES",
  GET_COUNTRIES: "GET_COUNTRIES",
};

export const Mutation = {
  SET_CITIES: "SET_CITIES",
  SET_COUNTRIES: "SET_COUNTRIES",
  LOADING_START: "LOADING_START",
  LOADING_STOP: "LOADING_STOP",
  TOGGLE_EDIT_OVERLAY: "TOGGLE_EDIT_OVERLAY",
};
