export const Action = {
  GET_CITIES: "GET_CITIES",
  GET_COUNTRIES: "GET_COUNTRIES",
  TOGGLE_LOADING: "TOGGLE_LOADING",
};

export const Mutation = {
  SET_CITIES: "SET_CITIES",
  SET_COUNTRIES: "SET_COUNTRIES",
  TOGGLE_LOADING: "TOGGLE_LOADING",
};
