version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "gegoune"
    groups:
      gha:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "gegoune"
    groups:
      npm-non-breaking:
        update-types:
          - "minor"
          - "patch"
      npm-breaking:
        update-types:
          - "major"
