customSyntax: "postcss-scss"
overrides:
  - files:
      - "**/*.vue"
    customSyntax: "postcss-html"
extends:
  - stylelint-config-standard
  - stylelint-config-recommended
  - stylelint-config-standard-scss
  - stylelint-config-recommended-scss
  - stylelint-config-recommended-vue
  - stylelint-config-recommended-vue/scss
  - stylelint-config-recess-order
  - stylelint-config-css-modules
rules:
  declaration-property-value-no-unknown: true
ignoreFiles:
  - "**/*.js"
  - "**/*.ts"
  - ".*.cjs"
