export const Action = {
  DATA_NOT_RETRIEVED: "DATA_NOT_RETRIEVED",
  DATA_RETRIEVED: "DATA_RETRIEVED",
  GET_DATA: "GET_DATA",
};

export const Mutation = {
  SET_ASCENTS: "SET_ASCENTS",
  SET_CRAGS: "SET_CRAGS",
  SET_DATA_NOT_RETRIEVED: "SET_DATA_NOT_RETRIEVED",
  SET_DATA_RETRIEVED: "SET_DATA_RETRIEVED",
  SET_GRADES: "SET_GRADES",
  SET_ROUTES: "SET_ROUTES",
  SET_SECTORS: "SET_SECTORS",
  SET_STYLES: "SET_STYLES",
};
