export const Action = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER",
  SHOW_COMPONENT: "SHOW_COMPONENT",
};

export const Mutation = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  SHOW_COMPONENT: "SHOW_COMPONENT",
};
