export const Action = {
  DATA_NOT_RETRIEVED: "DATA_NOT_RETRIEVED",
  DATA_RETRIEVED: "DATA_RETRIEVED",
  GET_DATA: "GET_DATA",
};

export const Mutation = {
  SET_DATA_NOT_RETRIEVED: "SET_DATA_NOT_RETRIEVED",
  SET_DATA_RETRIEVED: "SET_DATA_RETRIEVED",
  SET_DATA: "SET_DATA",
  SET_GYMS: "SET_GYMS",
  SET_SESSIONS: "SET_SESSIONS",
};
