name: Linters

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: "17"
      - uses: xt0rted/stylelint-problem-matcher@v1
      - name: npm install
        run: npm install
      - name: stylelint
        run: npm run ci:lint:css
      - name: eslint
        run: npm run ci:lint
