name: Linters

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions-hub/stylelint@v1.1.3
        env:
          PATTERN: "src/**/*.{vue,css,scss,html}"
